### ISSUE TITLE
[TASK] - Er wordt geen git repo geïnitialiseerd zoals verwacht

### ISSUE THREAD

**Issue by SanderKleykens** [milieuinfo/webcomponent-vl-blueprint#12]
** Beschrijving**
Op https://www.milieuinfo.be/confluence/display/FEO/Webcomponenten+workflow staat:

> Wanneer gebruik gemaakt werd van de vl-blueprint zal de optie "push an existing repository from the command line" van toepassing zijn.

Dit werkt echter niet, omdat vl-blueprint nog geen git repo maakt, alle files toevoegt en een commit doet in de aangemaakte directory.

**Hoe te reproduceren**
Gewoon de clone.sh aanroepen, stappen doorlopen en proberen te pushen naar een nieuwe github repo.

**Gewenst gedrag**
Van de nieuw aangemaakte directory wordt ook meteen een git repo gemaakt, worden alle files toegevoegd aan de index en wordt er een commit aangemaakt.

**Comment by coemans** [comment]
@cambiph een 'git init' uitvoeren op het einde zou dit probleem moeten oplossen.
