### ISSUE TITLE
[BUG] - Verkeerde link naar API

### ISSUE THREAD

**Issue by pascalriquier** [milieuinfo/webcomponent-vl-blueprint#13]
De URI die gegenereerd wordt om te linken naar de API van een webcomponent is verkeerd (volgens @coemans moeten er nog ergens '-' gestripped worden ...)

**Comment by coemans** [comment]
@cambiph probleem stelt zich wanneer er een '-' in de naam zit.

**Comment by cambiph** [comment]
Already fixed.
