### ISSUE TITLE
[BUG] - Verkeerde link naar bash?

### ISSUE THREAD

**Issue by pascalriquier** [milieuinfo/webcomponent-vl-blueprint#14]
Volgens @SanderKleykens moet het pad naar bash vrijwel zeker /usr/bin/env ipv /usr/env/bin zijn

**Comment by SanderKleykens** [comment]
Ja, zegt het hem maar eens goed, @pascalriquier (╯°□°）╯︵ ┻━┻

**Comment by kevcraey** [comment]
niet meer relevant na bash - > JS
