### ISSUE TITLE
[FEATURE] - JSDoc beschrijving aanvullen

### ISSUE THREAD

**Issue by coemans** [milieuinfo/webcomponent-vl-blueprint#17]
**Wat moet er gebeuren**
Bij het clone script wordt een beschrijving gevraagd. Deze wordt momenteel gebruikt in de package.json en README.md, maar zou ook gebruikt kunnen worden in de JSDoc bij @classdesc van het .src.js bestand.

**Comment by cambiph** [comment]
Fixed in https://github.com/milieuinfo/webcomponent-vl-blueprint/commit/9fb4701d31a9dabdd131ebb405652987838a55a9
